resources:
  repositories:
    - repository: templates
      name: jmboutou/templates
      type: git

jobs: 
- template: terraform-validate.yml@templates
  parameters:
    terraformVersion: 'latest'
    serviceprincipal: 'az-sconnection'
    resourcegroup: 'rg-azdvo'
    storageAccountName: 'stazdvo'
    storageContainerName: 'stcontainer'
    storageKey: 'terraform.tfstate'

- template: terraform-deploy.yml@templates
  parameters:
    terraformVersion: 'latest'
    serviceprincipal: 'az-sconnection'
    resourcegroup: 'rg-azdvo'
    storageAccountName: 'stazdvo'
    storageContainerName: 'stcontainer'
    storageKey: 'terraform.tfstate'
    deployEnv: 'dev'

